### ISSUE TITLE
benchmark observations: `get` performance decreases with number of inserted keys

### ISSUE THREAD

**Issue by snd** [paritytech/paritydb#45]
...even on repeated access to the same key.

i wrote a benchmark that inserts `n` address keys with a zero sized value (setup, not part of benchmark) and then repeatedly gets addresses from a subset of size `m`. where `m <= n`. i'll replace the zero sized value with an account struct later to better approximate a real use case.

benchmark is here: https://github.com/paritytech/paritydb/blob/cb4f0592b7169a7f0b9bf72f26c5c9dc697c04e0/benchmarks_realworld/benches/account.rs

you can run it by checking out https://github.com/paritytech/paritydb/tree/realworld_benchmarks, executing `cd benchmarks_realworld` and `cargo bench`.

results for me are:

```
$ cargo bench 
   Compiling benchmarks_realworld v0.1.0 (file:///Users/basilisk/workspace/paritydb/benchmarks_realworld)
    Finished release [optimized] target(s) in 6.43 secs
     Running /Users/basilisk/workspace/paritydb/target/release/deps/benchmarks_realworld-dc8a38a93e7da761

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running /Users/basilisk/workspace/paritydb/target/release/deps/account-424bf01033ff681c

running 15 tests
test paritydb_from_10000_inserted_get_10000_addresses ... bench:     572,958 ns/iter (+/- 421,115)
test paritydb_from_10000_inserted_get_1000_addresses  ... bench:   1,166,766 ns/iter (+/- 236,874)
test paritydb_from_10000_inserted_get_100_addresses   ... bench:   1,245,035 ns/iter (+/- 191,830)
test paritydb_from_10000_inserted_get_10_addresses    ... bench:   1,264,291 ns/iter (+/- 126,440)
test paritydb_from_10000_inserted_get_1_addresses     ... bench:     698,889 ns/iter (+/- 361,905)
test paritydb_from_1000_inserted_get_1000_addresses   ... bench:      20,647 ns/iter (+/- 5,813)
test paritydb_from_1000_inserted_get_100_addresses    ... bench:      41,140 ns/iter (+/- 12,247)
test paritydb_from_1000_inserted_get_10_addresses     ... bench:      42,182 ns/iter (+/- 9,739)
test paritydb_from_1000_inserted_get_1_addresses      ... bench:      42,313 ns/iter (+/- 12,625)
test paritydb_from_100_inserted_get_100_addresses     ... bench:       2,079 ns/iter (+/- 548)
test paritydb_from_100_inserted_get_10_addresses      ... bench:       3,493 ns/iter (+/- 1,437)
test paritydb_from_100_inserted_get_1_addresses       ... bench:       3,547 ns/iter (+/- 1,657)
test paritydb_from_10_inserted_get_10_addresses       ... bench:         275 ns/iter (+/- 74)
test paritydb_from_10_inserted_get_1_addresses        ... bench:         495 ns/iter (+/- 351)
test paritydb_from_1_inserted_get_1_addresses         ... bench:         172 ns/iter (+/- 39)

test result: ok. 0 passed; 0 failed; 0 ignored; 15 measured; 0 filtered out
```

**does this look as expected?**

what stands out to me is that performance degrades with increased number of inserted keys.
there seems to be no caching since `test paritydb_from_10000_inserted_get_1_addresses     ... bench:     698,889 ns/iter (+/- 361,905)` takes significantly longer than `test paritydb_from_1_inserted_get_1_addresses         ... bench:         172 ns/iter (+/- 39)`

for comparison these are the results of doing `cd benchmarks` and  `cargo bench`:

```
cargo bench
   Compiling benchmarks v0.1.0 (file:///Users/basilisk/workspace/paritydb/benchmarks)
    Finished release [optimized] target(s) in 8.40 secs
     Running /Users/basilisk/workspace/paritydb/target/release/deps/benchmarks-85dc97a6dcfc84b3

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running /Users/basilisk/workspace/paritydb/target/release/deps/get-cff4f4ae56bef3fe

running 6 tests
test lmdb_dummy_get          ... bench:         200 ns/iter (+/- 111)
test lmdb_dummy_get_null     ... bench:         180 ns/iter (+/- 166)
test paritydb_dummy_get      ... bench:         206 ns/iter (+/- 70)
test paritydb_dummy_get_null ... bench:          17 ns/iter (+/- 10)
test rocksdb_dummy_get       ... bench:         530 ns/iter (+/- 162)
test rocksdb_dummy_get_null  ... bench:         250 ns/iter (+/- 53)

test result: ok. 0 passed; 0 failed; 0 ignored; 6 measured; 0 filtered out
```

`test paritydb_from_1_inserted_get_1_addresses         ... bench:         172 ns/iter (+/- 39)`
corresponds to `test paritydb_dummy_get      ... bench:         206 ns/iter (+/- 70)`

**Comment by tomusdrw** [comment]
That's really interesting! We need to profile that. I'm curious why the performance gets better (!) when you retrieve more keys?

**Comment by tomusdrw** [comment]
Hmm, just realised that you are using default `key_size_length=8` right? So that creates a database that is able to fit 2^8 elements so I think the actualy issue is that we allow you to insert more keys than the db can handle, which most likely breaks some of our assumptions, and while you are trying to retrieve the keys you are scanning the entire database.

**Comment by snd** [comment]
@tomusdrw  i set `key_len` to `Address::len()` which is `20` as i've just confirmed:
https://github.com/paritytech/paritydb/blob/cb4f0592b7169a7f0b9bf72f26c5c9dc697c04e0/benchmarks_realworld/benches/account.rs#L35

i can't find `key_size_length` anywhere:
https://github.com/paritytech/paritydb/search?utf8=%E2%9C%93&q=key_size_length&type=

shouldn't the database not allow inserting keys that have a different size from `key_len`?

**Comment by tomusdrw** [comment]
Database is validating the key size indeed.

I meant `key_index_length` - this tells you how many bits of the key are used to construct the prefixes. This also has direct impact on the database size (and the number of records we can actually store).
Although, I tested that locally as well and getting similar results (even though with increased `key_index_length`).
```
running 15 tests
test paritydb_from_10000_inserted_get_10000_addresses ... bench:     280,575 ns/iter (+/- 426,674)
test paritydb_from_10000_inserted_get_1000_addresses  ... bench:     629,927 ns/iter (+/- 140,400)
test paritydb_from_10000_inserted_get_100_addresses   ... bench:     661,054 ns/iter (+/- 116,152)
test paritydb_from_10000_inserted_get_10_addresses    ... bench:     666,414 ns/iter (+/- 109,137)
test paritydb_from_10000_inserted_get_1_addresses     ... bench:     550,823 ns/iter (+/- 44,821)
test paritydb_from_1000_inserted_get_1000_addresses   ... bench:      24,961 ns/iter (+/- 2,641)
test paritydb_from_1000_inserted_get_100_addresses    ... bench:      48,772 ns/iter (+/- 2,750)
test paritydb_from_1000_inserted_get_10_addresses     ... bench:      51,041 ns/iter (+/- 3,915)
test paritydb_from_1000_inserted_get_1_addresses      ... bench:      47,484 ns/iter (+/- 7,254)
test paritydb_from_100_inserted_get_100_addresses     ... bench:       2,312 ns/iter (+/- 152)
test paritydb_from_100_inserted_get_10_addresses      ... bench:       4,314 ns/iter (+/- 272)
test paritydb_from_100_inserted_get_1_addresses       ... bench:       4,370 ns/iter (+/- 216)
test paritydb_from_10_inserted_get_10_addresses       ... bench:         299 ns/iter (+/- 13)
test paritydb_from_10_inserted_get_1_addresses        ... bench:         549 ns/iter (+/- 79)
test paritydb_from_1_inserted_get_1_addresses         ... bench:         163 ns/iter (+/- 11)
```

**Comment by snd** [comment]
i see. 

interesting that you're getting the same results even with increased `key_index_bits`.

was able to confirm that.

i extended the benchmarks to also bench with a larger `key_index_bits=16`. `2^16 = 65,536` = plenty of space.

results:

```
test paritydb_from_10000_inserted_get_10000_addresses                      ... bench:     650,522 ns/iter (+/- 406,318)
test paritydb_from_10000_inserted_get_10000_addresses_large_key_index_bits ... bench:     730,042 ns/iter (+/- 390,310)
test paritydb_from_10000_inserted_get_1000_addresses                       ... bench:   1,102,101 ns/iter (+/- 182,160)
test paritydb_from_10000_inserted_get_1000_addresses_large_key_index_bits  ... bench:   1,139,959 ns/iter (+/- 252,144)
test paritydb_from_10000_inserted_get_100_addresses                        ... bench:   1,281,373 ns/iter (+/- 447,923)
test paritydb_from_10000_inserted_get_100_addresses_large_key_index_bits   ... bench:   1,236,483 ns/iter (+/- 181,034)
test paritydb_from_10000_inserted_get_10_addresses                         ... bench:   1,219,407 ns/iter (+/- 119,087)
test paritydb_from_10000_inserted_get_10_addresses_large_key_index_bits    ... bench:   1,237,929 ns/iter (+/- 163,364)
test paritydb_from_10000_inserted_get_1_addresses                          ... bench:     683,335 ns/iter (+/- 372,089)
test paritydb_from_10000_inserted_get_1_addresses_large_key_index_bits     ... bench:     660,731 ns/iter (+/- 286,244)
test paritydb_from_1000_inserted_get_1000_addresses                        ... bench:      20,943 ns/iter (+/- 10,939)
test paritydb_from_1000_inserted_get_1000_addresses_large_key_index_bits   ... bench:      20,869 ns/iter (+/- 10,036)
test paritydb_from_1000_inserted_get_100_addresses                         ... bench:      41,006 ns/iter (+/- 15,698)
test paritydb_from_1000_inserted_get_100_addresses_large_key_index_bits    ... bench:      43,597 ns/iter (+/- 17,361)
test paritydb_from_1000_inserted_get_10_addresses                          ... bench:      43,098 ns/iter (+/- 13,158)
test paritydb_from_1000_inserted_get_10_addresses_large_key_index_bits     ... bench:      45,111 ns/iter (+/- 23,147)
test paritydb_from_1000_inserted_get_1_addresses                           ... bench:      42,438 ns/iter (+/- 19,002)
test paritydb_from_1000_inserted_get_1_addresses_large_key_index_bits      ... bench:      38,751 ns/iter (+/- 34,612)
test paritydb_from_100_inserted_get_100_addresses                          ... bench:       2,146 ns/iter (+/- 576)
test paritydb_from_100_inserted_get_100_addresses_large_key_index_bits     ... bench:       2,146 ns/iter (+/- 608)
test paritydb_from_100_inserted_get_10_addresses                           ... bench:       3,892 ns/iter (+/- 1,157)
test paritydb_from_100_inserted_get_10_addresses_large_key_index_bits      ... bench:       3,558 ns/iter (+/- 2,945)
test paritydb_from_100_inserted_get_1_addresses                            ... bench:       4,192 ns/iter (+/- 1,105)
test paritydb_from_100_inserted_get_1_addresses_large_key_index_bits       ... bench:       4,243 ns/iter (+/- 2,688)
test paritydb_from_10_inserted_get_10_addresses                            ... bench:         296 ns/iter (+/- 93)
test paritydb_from_10_inserted_get_10_addresses_large_key_index_bits       ... bench:         307 ns/iter (+/- 116)
test paritydb_from_10_inserted_get_1_addresses                             ... bench:         539 ns/iter (+/- 390)
test paritydb_from_10_inserted_get_1_addresses_large_key_index_bits        ... bench:         519 ns/iter (+/- 360)
test paritydb_from_1_inserted_get_1_addresses                              ... bench:         187 ns/iter (+/- 129)
test paritydb_from_1_inserted_get_1_addresses_large_key_index_bits         ... bench:         181 ns/iter (+/- 84)
```

increasing `key_index_bits` doesn't improve things

---

> Database is validating the key size indeed.

good

**Comment by tomusdrw** [comment]
I think there is something wrong happening anyway. iirc `key_index_bits` should actually limit the database size, so you should never be able to insert more elements than `2^key_index_bits` (in future we will re-organize the database, but for now we don't). Something's fishy.

**Comment by snd** [comment]
ok! i'll keep writing realworld benchmarks, do some quickchecking and maybe even some fuzzing to find things like this

**Comment by snd** [comment]
i'd also be interested in debugging this problem and appreciate any pointers

**Comment by tomusdrw** [comment]
@snd Ok, figured out what is wrong. You are creating one journal entry for each address you insert.
After all addresses are inserted you are calling `flush_journal(1)` but it only consumes one journal.

You either need to:
- flush the entire journal: `flush_journal(None)` (but it takes quite a long time for ~10k journal entries)
- or insert everything in a single transaction (and obviously flush then)

After the change:
```
test paritydb_from_10000_inserted_get_10000_addresses ... bench:         190 ns/iter (+/- 3)
test paritydb_from_10000_inserted_get_1000_addresses  ... bench:         185 ns/iter (+/- 3)
test paritydb_from_10000_inserted_get_100_addresses   ... bench:         191 ns/iter (+/- 7)
test paritydb_from_10000_inserted_get_10_addresses    ... bench:         183 ns/iter (+/- 8)
test paritydb_from_10000_inserted_get_1_addresses     ... bench:         182 ns/iter (+/- 53)
test paritydb_from_1000_inserted_get_1000_addresses   ... bench:         188 ns/iter (+/- 51)
test paritydb_from_1000_inserted_get_100_addresses    ... bench:         181 ns/iter (+/- 13)
test paritydb_from_1000_inserted_get_10_addresses     ... bench:         178 ns/iter (+/- 10)
test paritydb_from_1000_inserted_get_1_addresses      ... bench:         182 ns/iter (+/- 26)
test paritydb_from_100_inserted_get_100_addresses     ... bench:         179 ns/iter (+/- 7)
test paritydb_from_100_inserted_get_10_addresses      ... bench:         178 ns/iter (+/- 9)
test paritydb_from_100_inserted_get_1_addresses       ... bench:         177 ns/iter (+/- 26)
test paritydb_from_10_inserted_get_10_addresses       ... bench:         178 ns/iter (+/- 12)
test paritydb_from_10_inserted_get_1_addresses        ... bench:         182 ns/iter (+/- 18)
test paritydb_from_1_inserted_get_1_addresses         ... bench:         184 ns/iter (+/- 49)
```

**Comment by tomusdrw** [comment]
Ok, now it also make sense that you didn't get insert errors (even though the database was full) - these new inserts were just part of the journal - they were never written to the database.

You need to increase `key_index_bits` or otherwise `flush_journal()` will throw that there is not enough space in the database.

**Comment by snd** [comment]
glad you figured that out! also glad there's no bug.

i just reproduced everything. i'm getting panics as expected as well with the smaller `key_index_bits`.

do you think this benchmark (or part of it) is worth keeping to test for regressions in the future?

while we're at it: what other benchmarks and tests do you think are most important right now?

**Comment by tomusdrw** [comment]
This benchmark is definitely good to have (although might be better to just use `ethcore-bigint` or `ethereum-types` (not published yet, contact marek) instead of the entire `parity-utils`).

I think it would be good to have a benchmark that creates many prefix collisions (handling collisions is not implemented properly yet).
I.e:
1. Get random address A
2. Insert A, A+1, A+2, ... A+32 (same prefix)
3. let (prefix, rest) = A; Insert (prefix+1, rest), (prefix+1, rest+2), etc.
Check the performance of queries.

Some other benchmarks:
- Journal speed (reading from journal/many journals, flushing journal)
- Variable record size benchmark (how data length affects querying of other keys)
- Insert/delete benchmarks: same data as for prefix collision, but then remove some of the entries and insert more, etc (the database needs to re-organize a bit to keep the keys consecutive so it will be good to measure it).
- Iteration benchmark (empty database, full database, half full database, etc).

**Comment by snd** [comment]
@tomusdrw thanks! i'll get on that

**Comment by snd** [comment]
@debris what's the recommended way/crate of using `bigint::hash::H160` here? (see last comment by @tomusdrw)

**Comment by snd** [comment]
closing this because the original issue is solved and the benchmark continues here: https://github.com/paritytech/paritydb/pull/50
