### ISSUE TITLE
obscure possible bug: panic "destination and source slices have different lengths"

### ISSUE THREAD

**Issue by snd** [paritytech/paritydb#46]
i wrote a simple quickcheck that checks getting an inserted value again using the same key:
https://github.com/paritytech/paritydb/blob/3b9ff50be8af4b5ab15d9854cc776c8775871c75/quickchecks/tests/quickcheck.rs

it fails:

```
$ cargo test
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running /Users/basilisk/workspace/paritydb/target/debug/deps/quickcheck-fe4433715c512650

running 1 test
test can_get_inserted_value ... FAILED

failures:

---- can_get_inserted_value stdout ----
        thread 'can_get_inserted_value' panicked at 'destination and source slices have different lengths', src/libcore/slice/mod.rs:671:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'can_get_inserted_value' panicked at 'destination and source slices have different lengths', src/libcore/slice/mod.rs:671:8
thread 'can_get_inserted_value' panicked at 'destination and source slices have different lengths', src/libcore/slice/mod.rs:671:8
thread 'can_get_inserted_value' panicked at 'destination and source slices have different lengths', src/libcore/slice/mod.rs:671:8
thread 'can_get_inserted_value' panicked at 'destination and source slices have different lengths', src/libcore/slice/mod.rs:671:8
thread 'can_get_inserted_value' panicked at 'destination and source slices have different lengths', src/libcore/slice/mod.rs:671:8
thread 'can_get_inserted_value' panicked at 'destination and source slices have different lengths', src/libcore/slice/mod.rs:671:8
thread 'can_get_inserted_value' panicked at 'destination and source slices have different lengths', src/libcore/slice/mod.rs:671:8
thread 'can_get_inserted_value' panicked at '[quickcheck] TEST FAILED (runtime error). Arguments: ([0], [], 1)
Error: "destination and source slices have different lengths"', /Users/basilisk/.cargo/registry/src/github.com-1ecc6299db9ec823/quickcheck-0.4.1/src/tester.rs:147:27


failures:
    can_get_inserted_value

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test quickcheck'
```

relevant part: `Arguments: ([0], [], 1)`

i've created a failing test that exposed the problem:
https://github.com/paritytech/paritydb/blob/3b9ff50be8af4b5ab15d9854cc776c8775871c75/paritydb/tests/tests.rs#L312

panic occurs with `key_index_bits=1` or `=2`

backtrace suggests that it happens during `flush_journal`.

**Comment by snd** [comment]
i think i'm onto the problem and will try to fix it

**Comment by snd** [comment]
`bytes::Metadata::len` might be broken:
https://github.com/paritytech/paritydb/blob/8f016073c890e83ee3c3a468695f74d18869c189/paritydb/src/metadata.rs#L86

if `prefix_bits` is `1` or `2` then `((1 << prefix_bits) >> 3)` is 0 which makes consumers currently allocate 10 bytes (`Metadata::VERSION_SIZE + Metadata::OCCUPIED_SIZE`).

here however https://github.com/paritytech/paritydb/blob/8f016073c890e83ee3c3a468695f74d18869c189/paritydb/src/metadata.rs#L70

`data` would have size 10. `data[leaves_offset..]` would have 0 size because `leaves_offset` is 10 but `leaves` would have size 1 for `prefix_bits = 1`

**Comment by tomusdrw** [comment]
Make sense, should probably be something like `(((1 << prefix_bits) + 7) >> 3)`

**Comment by snd** [comment]
that seems to fix it! i've done some small refactoring to metadata. will open a PR with that and the fix tomorrow
